apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    ## Les éléments suivants sont requis par ClusterTool et NE PEUVENT PAS être supprimés
    # Assurez-vous que le VIP est différent de tous les IPs des masters
    VIP: 192.168.0.254
    ## Définit l'IP du MasterNode
    # Veuillez noter que nous ne supportons que x86_64 pour le premier nœud, ARM NE FONCTIONNERA PAS par défaut
    MASTER1IP: 192.168.0.201
    # Définit le passerelle pour tous les nœuds
    GATEWAY: 192.168.0.1
    # Définit la plage d'IP que MetalLB est autorisé à utiliser
    METALLB_RANGE: 192.168.0.202-192.168.0.253
    # IP que NGINX utilisera pour exposer les ressources d'entrée. Internal fait référence à l'entrée de NGINX sur le réseau local uniquement, pas de redirection de port au niveau du routeur.
    NGINX_INTERNAL_IP: 192.168.0.202
    # IP que NGINX utilisera pour exposer les ressources d'entrée. Internal se réfère à l'entrée LAN et WAN de NGINX, DO port-forward au niveau du routeur.
    NGINX_EXTERNAL_IP: 192.168.0.203
    # IP Blocky DNS sera exposé sur
    BLOCKY_IP: 192.168.0.204
    # Définit l'IP du tableau de bord Kubernetes. Doit être dans METALLB_RANGE et ne pas être en cours d'utilisation
    DASHBOARD_IP: 192.168.0.205
    ## Configure Traefik, ClusterIssuer et Blocky pour ce domaine, en utilisant ces informations d'identification.
    # Le domaine est le niveau de base le plus élevé de votre domaine, donc sans sous-domaine, exemple : truecharts.org, pas somesite.truecharts.org
    # Pour désactiver, veuillez consulter les commentaires dans leurs fichiers helm-values.yaml respectifs !
    # Lorsque cette option est désactivée, veuillez utiliser des valeurs de remplacement à la place.
    DOMAIN_0: yong.ovh
    DOMAIN_0_EMAIL: aorusnyco@gmail.com
    DOMAIN_0_CLOUDFLARE_TOKEN: VB-Egs_XQukP2A579r8jCwwksPc6Og0MwAvloyUs
    # Utilisé pour générer automatiquement une paire sshkey pour FluxCD
    # Doit commencer par ssh://
    # Veillez à ce que l'URL ne contienne PAS de caractères spéciaux, à l'exception de « - »
    GITHUB_REPOSITORY: ssh://git@github.com:Nicoyong/talos-cluster.git
    ## Décommenter et adapter pour configurer automatiquement vos identifiants dockerhub
    ## Cela devrait permettre d'éviter une grande partie des limites de taux potentielles.
    # DOCKERHUB_USER: dockerhub-username
    # DOCKERHUB_PASSWORD: dockerhub-password
    ## NE PAS MODIFIER
    PODNET: 172.16.0.0/16
    SVCNET: 172.17.0.0/16
    #--------------------
    ## minio S3
    S3_URL: http://192.168.0.200:9000
    S3_ACCESKEY: RQKA6l7WNtA3ygs4qy6O
    S3_SECRETKEY: XcKjqvv0jLjC4RHFzNrwOdRjUdB8tUcC5jKYcRfs
    S3_ENCRKEY: Z5Lhmely8XOdSDQyjhp9rEmXhBdIWu6jfzoU3hyOzDU=
    ## Nextcloud
    NEXTCLOUD_USER: Nicolas
    NEXTCLOUD_PASSWORD: fannyfanny
    NEXTCLOUD_NFS_PATH: /mnt/Raid/Nextcloud
    ## Jellyfin
    JELLYFIN_NFS_PATH: /mnt/Seag/Multimedia
    ##qbittorrent
    QBITTORRENT_TCP_PORT: "58489"
    QBITTORRENT_UDP_PORT: "58489"
    QBITTORRENT_PATH: /mnt/M.2/Downloads
    #--------------------
    #----IP------
    ## IP metallb
    QBITTORRENT_IP: 192.168.0.206
    RUSTDESK_IP: 192.168.0.208
    ## IP externe
    TRUENAS_IP: 192.168.0.200
    HOMEASSISTANT_IP: 192.168.0.2
    HOMEASSISTANT_PORT: "8123"
    PRUSA_IP: 192.168.0.101
    PRUSA_PORT: "80"
    MESANGES_IP: 176.170.87.92
    MESANGES_PORT: "1635"
    AI_IP: 192.168.0.10
    AI_PORT: "3000"
    OLLAMA_IP: 192.168.0.10
    OLLAMA_PORT: "11434"
    CLUSTERNAME: main
