apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mSM6wDTgeRtb1SGuSJZYOhDo7HnqCls2CfrbdjfSISlx5ZJrkM8xrcMFbMXfIwRQPEiLILY5/vgtGeGNbeulgrYXkpRSwgZSIegkk5EtYzfHPL70rHo2baNNCXbZBacnkKEdgyRSN89XORDXxr7fuAiO02TywG9hdInkwfhoftQ5tTWYEgNHvHOjdg7iRfi8QE14TPA/G83BGfk6ZXlqi+uFoUOJfhS4k74Qc08i5kz8+QqoFbScjYCRs8VlhBGLBKV6hLS+jo5wqkwvttIjowNjJDIjrIueaqe2MB3eRKMwdGdR9h9BlJrc5jZBsDsq5QV8GX1nz7B9T2Qgd4VrC7AeNCmbrSQsO6Nkrybi9oRJ4RX84W1VV0jF1U/6AzAQ,iv:zkOPA3Oz1HJa8ynMFQlhNbEKWofnw1Ib/H6gLpBDlis=,tag:DqdYgpmSr0AB9kuGTrapNQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:3LCPmsgTeouoX1s7cv25Lb/Dwc/lq3jEJaSmp4U4yTbi15dJDhr6RN5CNXDXa945fjhNxdZwyxspfL4UWji3Lu3c1etkQEiYTrfDC0pxfpqeUAO4AjsA7nNJBDVi1pfExMlj9HJUBFPI8umpB1hrWOujWd/EnwvtOnNpYVSeiAzcLfKTmY4zO7TFdKa0VPBKECVbEVaiuC+dVCkrTlXJ4qtmCp5Hp4V6rCakVYHmxq9E0rmOXFr4mtO8mEljyCMiJdJcufnQ0svYWKSOHA==,iv:LuSN+UOpfN1aSzBvKDpp5k+MVyloXKZyXGD2sJYMbGs=,tag:684mCGiDSy+OiEjTRVUQxw==,type:str]
    known_hosts: ENC[AES256_GCM,data:qS7881h01nfq+1FElxVyQAS/VqIfArwFDZzF1oZ4iyZz/nTRsrMU8N2XmUBOHhrfEzx9nKF6pqYlneJymuOkQKNnfVDRTgeGduoxJw0DLcdCKscT1iSchx1BCdsCHAYRAxNTNeeaIfttPVrbFF9ITE1qwf44c3A6bEEoM887Htc5bHaLa4NEWtNqRcbzXnBgPPM6qRFjJiqhh2WsWP7FmQ8AoTTkZhMoYWPH,iv:VX57bZB1tPw7ZXA/XTShYWChG33lBE4dmDaLjcJielg=,tag:Txq97c1iaFBuK25RPaRz+g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxLzNPcVNHaGJIQ1oyQm83
            dEhORnhTRWhVTjN0YWxzN25UbW9Ia0g1cGdjCjhtaTFJeVQ3NUtzcEJoMGR1R25w
            SWRRM25Zd1RhMUhkdzhzM2FCYytDbzAKLS0tIDgyT0VuOWYwTHBaMlhnSURJcmZN
            TXovbit1VmFVcWJwV0RxZ0hEcFh4azAK58QcUcZCcLYX9rCpJq2J+lFDybF91pfh
            mrnJYxnxK+1GW2y7IQ2akjPBh+tp1kq2KjeGRrp27T/eeEpYRA5orQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:52:58Z"
    mac: ENC[AES256_GCM,data:8Wn0hGjJvZ70lxYvqN5N3EyuNV+r9Jnhperfxa3y7UwuEz5S562CsXWrD4gy+W2J3vXLi37orRV4v7Hg+c3TDy1z2JxLtooCCMD1Xbsc9zQmE+8OQi8X6L7gAoQ+H/gGUxBENQHqyumR7tqZiB5uIyuNm/GOsB2PgqWe4PyspI0=,iv:0ebI9i0fl5jAKVOCZEBOrp+v73zrWJRm+8jsz3TYr7I=,tag:yt1Aa9MYmCFq2OC6VvxdGA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
