apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5CNk9ocqm/5rIviPHrrwOsEc7LLoVBSF+XNGOUPEMpTaFcEWbswy2AcUCLparAgQe8QnqtX6ZvT66UC7MBz7TPF0F2TivYmp4mW9qnzBhcKoLrleOTLFdOQnXEIdziuPrx9+C2mymnxQz98orieCicKS66RhBOqBzyzsvlcp0X9MlggMU5OyCktl4BcuH/ZJkCIB6tpvartEhS6ze1G/taO+oksbC9S4Ua/V6E04sTBU94RBsOxWzmw25GqAnZlROmFcxs9K4fCE8M6Vu0yVIj+FmNjQuTZgrGbaxJH+xcpQp07dJ8zAVoYKhbwfGRFZJhUzAy02FFTsPjcmhhff7TPhNGv4FJON/58uhBKihq6wugVs3PwF5/Qe3oTK8F+M,iv:Sya9oZ7Bs370T36sRHFVvxPeJE0GM8dcFZYQ3JnLn9U=,tag:wjL9FUiVwyAEkw3ZUeK9mQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:pbQZZsWnTMFk2xMyMWrlzyigtno1WnLodeG/GY+oK+4jHHtf9FY98u/gRV2oh+CjQk1uc8j3J8PECm7PiQrWfpGZJXQn8qPbOWWR31UUFSiCrnyWZVpNfdz84gBxXNTnqGf1p4q8/paHx6uHwbUOF+J/5sMhv+vJ6gRP5nrNIlfUaPbkprfTjy8GHjgAkRGulW2wVN6eYg3Xl0ev8aPXUfq7NEvqqwXjYAKKj2TqvAmBzfWDzhxF+9Fl3VFCdAilcR3ZMqKQuCJJLhPOIQ==,iv:NUxynLgitMnPPzSZVX/bSnKCp9r0F982U86z2CDZ5AI=,tag:XqbMwxlH1MYaiuNx4vu4og==,type:str]
    known_hosts: ENC[AES256_GCM,data:7xZdv6kUUV+j0/c/e9nroCxAY7Lh142/Tt4r/aS29xUPkPRHXQ6XPrFcvbxp/P1COnqWVaZ5+6xgZSYHaCs8aR6ZUnpqMTezgnsBzcAHfXb+/OtjqFLmC5iCkMG0UTj+3KMnNI2hO0MDCDhdozq0EHRrkcXSrB9VVOQ9d42H6KChGtlmKd3OBgw9Z4oj5bWTv9aFmhHMIZlY4MTmr3XJ00VQ8mHxLEtk2ocL,iv:4ccTSq0F+NKgjuISSPHk9VhLT/UN7ZC7A/MzIM2KtZc=,tag:gh4bky3yG4DE8XwbqfI/eg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCemszbXlrTWVWdUJmODBs
            SXlPeDBaeTB4ZHFiTW1PcmtLemwzQVNGWWowCko2OFBmWTdYMk9hZit2Wm5oTVRG
            d0xkRlphZVZRYXFvYit1MnVnMUt2ejgKLS0tIFpTUG43UGk3ekhUNUdoNkJ5cEU3
            cDN6TnBYWDU1d25IYnJadXVEUXRVRkkK/bJ1N0blncQRI2ykCqRZznpf0NJK7QjN
            pzpxi0lgCUqkIaYUmr187Jl9QP0bw3qrZhpKHkNgjW20xQNMav3epg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T17:38:56Z"
    mac: ENC[AES256_GCM,data:7xCNJ3HXKZSv6NtIfHZL6CPSbQcyxL2pNBMTnEF8Rwaq/bVN3xIMlb76ivtZGAjLcDfXU0ikOH1kEqhGr3m8X8HS508EccazqNKlUGIoaaTWT3DpKqTlQDFUNojCx/dCLC2ZqbWqe2C01mQ04cJGJoIzwcd3rbZ0RN+RHuW+4Tk=,iv:cNBeEeHq6eK1XRWiXp+xzZUiAuppPPyRnWz95AehdOY=,tag:NT74lohqUFox8BCNwqC0Aw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
