apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bsXW7pLmLF7vsNa8pRO4MHzofwrD9w2w1cygYF0723xl6aJnAfbBWCYTYPuhaF963KQUdy/UFmuRnyuXreiXT2517DDuhp77Z5jqxW6OEBWYvsmy5SW93fMTyoDeQLQL9y+H32m6rf1RN1RL49xFhIppcBZz23jXHio1HBRkiIFJJ5rtNgZo1mtHr6IEK7CEq+6wh8pSwt1wg7WRYbPpBgGxeBN+ek7ofI9MGdopywUerb9W7N9QECpFJs3cGMNi5nUyJlsoKBjP9mrEYX5UZrv9WXc0SLohE8jtorRx2WUYTbJQc4Q6zyivlZODAbImrkT0fr9E4gDov8ReRXXwM5IByQSBMDZfU6O1B52in10zAQWJ9ry5Ofb6eV9s2Cme,iv:Zx4BxMW8osjA/cevncGm/Lr0r9vQpEVaaOXVvEU0jlI=,tag:QAsX+Cs9xpfCqJUK3lo8hg==,type:str]
    identity.pub: ENC[AES256_GCM,data:v1E4XVtHFdFQSM3YXik4rLyiqkNASRN48gclcMMar5Z/w2Bs17NAG62EnIeCNPFyJ7ygoN9+QfRIsv+zPhI0R+mrxIVyORBW9Nt7w7oZJsVOddQKJd94+02/c8Llu3GgsZu8beBW1mf1F5Vcwg7nxyIEphpbgdVnIGIvc6tj4dLTX0LmpQb2DtqivNxrJ9yJ9MmIEX1U3QaBrbXsHHELEFE1HCUI0v9UQUL2vttwQ1TwR08X2KlldDIa4fuY08CWqB0EHYSCcPaiI2cqXw==,iv:5IY3hbGJx/xYvLHyll8lg8SGZjEuLpDd9yy/CeEBQmU=,tag:9g0IvcD5TeH+zoLPIac83g==,type:str]
    known_hosts: ENC[AES256_GCM,data:f3KKPNRFA7MvX1SBuk+OQLsfTrPAzbYh2A9b4Wnd91UhZHDUoBR8mEQ2LGFctYWICsZVHp8Z+dxFvNlP4LInHn3E20XS+YgYCIpjXVHvF33kAarYfCKdKUKanCskRwelXDryFGZc6UFBKoNg2SoPBRyrFvMcE2QshaSP1YKwB3B0k2k+NnjbqELRIvpD1jx1p3MTTUGgxbAL9yj86Z7bflbY4K6ZrkJlL82L,iv:+hfLShMDkCAu03QAAdxDZNCWtslrqcY/P2Fn/0dr4qI=,tag:yhZfvCnQzFYgcX/w4nYeeg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTStHYTkzaTJXaVpiNks0
            YnB6K3dVenQ1VFZXYkl2VjA2KzVKcnk0WXdFCjhRVDM4emdmYm0zNCsvcUFKdnpt
            enBKa3FBbUlzbWZEKzhKNGpYT3N0eEEKLS0tIG5WMkNhRklSK3pGVnZ4bGRFcUtH
            R2NqTjQ3dy94cml4S0hKNjYyVUUyYmsKHn9e7YOZJQl2Eqs67if7oFCkcJFFOQFB
            EFSn7SAovSyCLcqQXi8jseO7MSILDYd6VozuPLBloqHUJK9EnPW0AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T18:53:59Z"
    mac: ENC[AES256_GCM,data:ifO1JaQ+oKBqUisTO7VZRILNUYDprpnT4SWpdYutg0MDepuZdhCLWrC0roGbwZ7Zx+loEFzXVAhFlly4Zc2JOvbR2UD5T1uXvrUM4F4vxicSa910S1P+BRuXo7daiZ7onFTHJiPMR2Fx9OBWR+TEPaN8aOEOpB0KcNLx1zFWhx0=,iv:vfrXDiHpZGAZbfpkSyebrrqi8zt1hzmMgSpEVbFxCYc=,tag:heWHhacfb7B3hbrz6XOIMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
