apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LstqUrC0goLmfkbl2AXlq6t5ekRt53w6LIR50nC28WyEPgU/6M5kcvrVv/lY5dTgScTm2kA8Kpbd0rrklIEuL2RmF9m8L6o80ut5/4jj7nBS4BF7ownnW2CpmxBy0onhHCv8e4ESSDv91HjRfz1Bkutr7u3rBWx5epr0U7sd79hTv4Jqvf9Eh451l9kPaBN69NvFMX4ouaC97rtb1F77BMx4JLej7z2k5kGK0AfHxcghblXxGT5R0F4q/4sKqMn9e1uYcJ1kGNkzWJWrpQIQOaQTPNwP8Kk8TJE5UYXcbKMdzeh3EKYO3qlrLQ1uT+6+6fXhnLRP3ntf5nY1NXRgSv29vDe4n9ASlM4nPKocgbIwCfOS9+ZTynWRZofC7nJ4,iv:dGCnW5BjY4KXfhY4mRaBCoJgJ+WlOiPnwLl7HtIftLM=,tag:IeXBWx4au0XY7Ew98e82Vw==,type:str]
    identity.pub: ENC[AES256_GCM,data:yFX71btHKXoCWfMz1cglfi3BEG/d0q178jq+2sPO1rRTGb5BZNyKzIBbSvRvBv8Rp0Gj/VUWt8FG8+ss/XHa160BvMKzmMTjgz+fredVNcKdQw2PHggL7OzavTqBTyQVquUyL4rYoIh6anzwv4YyRx49afyimGohUPNDJpL6FHztPeOglRJ9pyazA4gJSS2yB80KGzNZxda17XuxmSlhAZZtt0VlQGbjzjf3X9uvJAXW0ESBPw7KVQ692BeSOXmLhrANxQ6cQFJSDCRQvA==,iv:giUeVc1GiA7jXwnN5g5l1SBcpo8TvrBOXOGlwnQd89g=,tag:hxbkQlJgAssOR8bbBW0fKg==,type:str]
    known_hosts: ENC[AES256_GCM,data:J3kbZ5uLS/ShYn+D4Azrujm0D/usI4mfWcE1mmFhhmd+foG5fMCJJbp01xB5+XjCeMDK5sLThmSwPEPcHHVa/hG1/oBYLX2/Bfa4Lqq9pBGMw5PR0aTPRfnKh0WhAF3CGoRePA4KrQy4K8bk3u0fhtSpZIrWPMo4DMzhw4uXQQ/Ti9vRKQUg1CAUbNA3lDkItUpiHF4vxlzqZfoVs1wu+Km/MVyP5ma7+6hv,iv:7Ci5Ty8LRkKsOnH6KvlzF2NiCER8dqK/SHhJU4Fsddw=,tag:j1lUKi4wViJ+Ado/2c1DBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRHE2TUptN2hWY1NJS0hv
            K3RqU2tuS1lLM3dvWDRvckxTdzc4Skh6SFJJCjc2TjQ0TTNuV3dIRzQ3M1FMMjlV
            SU1jN09paHFoUzQ1bCtvS0J3aTZvWkEKLS0tIDB6WjVEZUFWR0dBVWg4dzRjL3RG
            eENaZWhPUTVqamJsTGpjMTNvYzh6cU0KBZpVGXoMK6HGuLzWQhiej1sqfplwnHp5
            MggmCb9moUPkKq38rolr/uApXgoC3jOC5caGYYwcfZgGSIYfjN93AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T12:56:25Z"
    mac: ENC[AES256_GCM,data:peMJUDj3eHPbfFr44+0kpalbP79yujAN16IihkbvEiAXQ9FAv9cMwNq4bVwFajAdelZqb4ArqN4uLcnNmUHvj65fxaYK/0Sr1JpeleRGWXiXTC556MF2Syzu8e4fYFKUkjirTu+p8Dg3k2CRricCELWEPiAsjtGkiSS+rjxE3tw=,iv:DteOv7Jw+yj+mpyCJ9/JU91sPs3RoniacstL71sOQNY=,tag:kk86dvPNeXrFCi/ZO/0DAw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
