apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: |
        -----BEGIN EC PRIVATE KEY-----
        MIGkAgEBBDC08OSsuOrr2NP/Blzv6MgWkiifiHm0AkRqLRBOIYnTJnMTsJM4lKfh
        rB4bZri4NjGgBwYFK4EEACKhZANiAAQSmEZKtWLc8AgbkHLpacvbyIQsUdW0nrmF
        3yGlhJop2YcOG0i2UOCOlLYBrLCuK1V4DAToe7SxvxlkD+ZU1bDLNYy/X2pmXzNP
        K2Hi8NuH98vsCUZ5XM8iPewyCNfEdi4=
        -----END EC PRIVATE KEY-----
    identity.pub: |
        ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBBKYRkq1YtzwCBuQculpy9vIhCxR1bSeuYXfIaWEminZhw4bSLZQ4I6UtgGssK4rVXgMBOh7tLG/GWQP5lTVsMs1jL9famZfM08rYeLw24f3y+wJRnlczyI97DII18R2Lg==
    known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
type: Opaque
