apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jVMuX+NsYsd4/cTd3obbEdPmFt+Wmbe1D6bZN7c/y6BZwRlvrUyBobN27fGNxAkT4r/PEjoYKtkNLW5s2eORk3neCxoxQRX7ap0qB8+TAWUZMe7XRvpT+jLZCVd6EyasYTqWYLe0Ra4BXNsRAvAj4BkhmgoyA+LU+HtYKe9fm4JaFcm37lGMpO8qH9HpZXHfPXnyoE3SHBFkJTC99y4rlB6saUYlUcI6yHJ6u7LLHL5cTq1bNbUQrO4CzY1q3NcADIjkUARIysUDEJrdXfhIHRY5CrKQ66or/4Eb55b2+p6FU5bC8S3mQ7Ls6WQmqZ7WCTC9aceGi+1d0cRc0MVE3Z/gtKE8kHs+g5w3Kvg+SB3utQgKYS03No7UF8gpjdYT,iv:Jh61snxOD51yPNbLxpbbrIlnt+yo7+6PwtNG3sLg7Jk=,tag:fuYRvYOc60RJrWIbG0bAig==,type:str]
    identity.pub: ENC[AES256_GCM,data:FyDPa8LfZE6QEYh/crvfoziHjLC/BiD0sA8HjH17mXs3nnHT8Dcdo8kXffcBz//b+3iGbhTaK8pJ32PqajAmnpf+SFeL9bJ7s2E7wanXQ2OFe5jdjqjUZKYcm9LJB4cgtJ5VcRts3n9QydZcO2ivUVw+RKLED+5yCRH0uaZ3q+V0aIG+P809Ngm3HUu6b14qDwUg+w1lOL/Nfo8Hpd0GlSb+8T/pAM3VRykOoIyBo0bY5TpqPEHX6RXhun8boD84oD1F1BXtx2pWemvGOw==,iv:u0bXNsj5wY+x2wpuxq1+cYbGRckZ0T6nibjAtqnW+fY=,tag:9Yj8dT+X9Fh5/wAcgzbIfA==,type:str]
    known_hosts: ENC[AES256_GCM,data:jKYHv509SiiZ/Jqw1AM6JHRo6aq1khGdQvCPpabNcevtEFQkX1JhEYfT8W8oaNKAfLUmMoABFGZ+LFCOcBJcGAKgV3d60/IvIUmuwbz9jjoKVZ3iUELRu5qN+IWt4vqZaaE0EtHmYn9n4k22HERTe1qSZ26RsYZ+qnpGfS3NR37TOcdueIpv5/1ErGlZKRWaoH/QU5gboB4706zKo9A9wyp3vqY83n2xHp5l,iv:b/VBE5bbOi0Wo4J0BMxAbwrhYrWv8oXOcoy23JT67r0=,tag:A+h9Io3fy5mAQHpRih8Sdw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQjArVGppMk84WGdTWnRx
            MDYwaHN3V3l2dWpGeHNzOVlsT3FDcVZwU3hjCjZmNnR6MnpXNDJPV2lvNGtZYW1R
            TjhYZE1UYWJFM2xibmJwMzdWdEJOVDgKLS0tIHYvYnFKdWZSK3lCUEZ6WWJqRG9U
            WHVvQ3QwSjhldFdFU1M5Znh0Yi94Q2MKkSdtJP5icFroDu96QjH+IbF2yyoYUb9R
            NUoAPHo10phbES2Tjiq1cHqWT0b+xzExyGpiEbVgd6QYIYnQyNOlVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T18:07:49Z"
    mac: ENC[AES256_GCM,data:S1zD8gmnh0xve2nvEjqXcN2DoiWkRgs5JCpO+L9La5zP72H3rXvygQ8d+qz4jTwxeqNLj8PlLHab5+eDDrtG5eYEpcibhwdYerUZpmuE/YEwIaKhzPDnwlZtFPHilPTb3yPT3lCb0FvZ83EPmUj8887fK0owHY9XQsW/MSsyDuU=,iv:w5VTUqxIVC2iVD6gpjFG7FlrTPxb9HRGop43/Sk+XAk=,tag:NhFckCpehqwAAlwIHYPypQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
