apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OhZgs8eX1x9CvoxdMCaCyqp0fjqPv1MTZKa3VbpERlII5PCYC+seEqhi248OZ5IXshxuRHYKaBWCikBjeMmeQiFqO0ySxU45GTEjgNYgmvNsNtj1TWPrlCY31L9KHTGa5wo/n3XjQgHU4F8KOL0bdjLVxkXRm1/jXPIwBPPwjWgUGxKeWqci/GMZxRV7xMdkfL8bbCkXNGblBdbf9YExe2GrrL/ozzG9g+eUZx+FWk89jFu/YI3aEQdK/gpTV2IvwejgLHxBlBeqEQB1lWBtypwcNinbGfwscnG7vp4xA9XS2HN9eyAuKqJKziSwmrL/D1dQSWA2pyWOBk8dBeyaOzWi5aPmTIBNIaX02Lpi532DoVpbkdOU4FJt8xdBOWPC,iv:mMXyGLz8Kinq19izWay16kfgreALFTSoPf27Mt27CFA=,tag:XkhI7GE1GiY3ZBKMDLJnNA==,type:str]
    identity.pub: ENC[AES256_GCM,data:A4ytgnvC+0kObN9twUWijCHatF8sKuUYFByOh/B3ConVaUFeOH/Ma4/zr3a4fWIxOpHoukogPWAxxR4FzIXLoCtU/E+NToPfJzlyTApTZiIj3q2PGqnkbTUHZlBMn9tb0jFjW8rQ9iZUN0kDVznfe30ZkN7/hSZffFS5ZrUNhwn1RUxPL4qsU2ZIgdU7waNaWALBEIKga3M3aUDpN+2Th59QKqxi/N/oHDEfRXPfuUumrkgLQAuz1aeE202q2Dd6QaWIRNz/70La+IWF8Q==,iv:+xs1JXtp1VtPHgb1d5kC3JA26MRzLFIpzpduBVhjp6k=,tag:KFf0wpm0Lw9XFQgQe46XGw==,type:str]
    known_hosts: ENC[AES256_GCM,data:kHqP50SbDzCefd8hopc42NHg6PFj2xSyuM0GP5iz7e1UyM0e5ZvpCxj//Azr2aahynMGnpmuhwASuYpnE1O5Yz9U5pd3p2ng+DpPMMMGWTZl1pYpI31PBR0cxD+rOJbDZ9OWHWTUO9OJFkIfgpxkrGG+RvbwSfcxm5wofMNfoVeTK53IKoHIToKNjfpssDW1+MrhkZ91UCsBASdbznQJn5PE8E8rY3GbCFl4,iv:KCw85JCy31YcHC+u/kxZkpypSTdHu80OP5r1CVLbCwo=,tag:PR3u2p/oAu9ESJVK/6v0Dw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bXNMQnpib0JoWmN6NFJH
            NGswNWVzcitSQk9teWF5MWx2bUoyaFZqa1VZCkJjWVJjR1lTR1IvSmtSSkpKMEkw
            SlZMTGJicjJUdEU5Si81b0o1ektUMWMKLS0tIEU0WSt6YkVSYW5Mc3c0SXZEMllX
            ei9wNEszWUp0QWxUdlpCNjViUmxIUnMKBI2Pk5YonbN6F/Bw2oSiNuIOek/Z/lUH
            o3icdph1J7XALPk0LZ2jejDqPtU2OnlfUgGfKTA+tSeIggFP6D/wDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T07:07:29Z"
    mac: ENC[AES256_GCM,data:u1GgFk68QonwfZCprTQ7owQAyt76w3dOHXTC0NTtQYVbZF6YrLmks9n862E1EvMpVBmI86IR1PZG2q+cj81mcIt9B1MTmkbCmP+bcx6lHE8ySLK4RT5XdFrSDDUSPnEXE7EfOJtLQXoMAo0BsfWQWZcPwLfBY3eSLCH/uMvk3t0=,iv:ETtm2jeWMz4qyyKckAEL+dc2MFBTsR4BP5yn9wzL83M=,tag:DV/J2ujXlP+upn83z1AU4A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
